name: Deploy to EC2

on:
  push:
    branches:
      - master  # or 'main' if your branch is named main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Copy files to EC2 using SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "~/visitor-logger"

    - name: SSH into EC2 and restart Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd visitor-logger
          docker stop visitor-app || true
          docker rm visitor-app || true
          docker build -t visitor-app .
          docker run -d -p 80:5000 --name visitor-app visitor-app
