name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.VISITOR_KEY_B64 }}" | base64 -d > visitor-key.pem
        chmod 600 visitor-key.pem

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i visitor-key.pem -r ./ ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/visitor-logger

    - name: SSH into EC2 and restart Docker container
      run: |
        ssh -o StrictHostKeyChecking=no -i visitor-key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ubuntu/visitor-logger
          docker stop visitor-container || true
          docker rm visitor-container || true
          docker build -t visitor-app .
          docker run -d --name visitor-container -p 80:5000 visitor-app
        EOF
